### ISSUE TITLE
As of PHP 7.4, this method can now throw exceptions

### ISSUE THREAD

**Issue by Zhythero** [Dhii/stringable-interface#4]

**Comment by XedinUnknown** [comment]
Yes, it can. But what of that?

**Comment by XedinUnknown** [comment]
What I meant is that this package sets PHP 5.3 as minimal requirement, and therefore all code here has to comply with that. When we drop that compatibility, we will handle that accordingly.

Also please note that PHP 8 is coming out in December 2020, and it will have a `Stringable` interface. See [RFC][].

[RFC]: https://wiki.php.net/rfc/stringable
